### PR TITLE
One-hot encode current location ID based on all possible locations, not just ones present

### PR DESCRIPTION
**Pull request by phildarnowsky**

### CODE REVIEW

**Comment by losvedir** [comment]
How does this affect pipeline time and dataset size?

`locations.csv` has a `line` column. The blue line only has about 100 rows, compared to about 2,000 in the file. It seems like it would be good to use the slimmed down set of features, if possible.

**Comment by phildarnowsky** [comment]
@losvedir as I mentioned in standup, I want to use all locations rather than filtering so that we can re-use the same pipeline for other routes, or a hypothetical all-route-predicting system.

This adds roughly 2,000 columns, and I'm running the pipeline now to get an idea of how long it takes.

**Comment by phildarnowsky** [comment]
@losvedir full encoding took a hair over ten minutes, which is where it was before, so we don't seem to be taking a hit there.

**Comment by losvedir** [comment]
And the size of the dataset? I guess if it's a sparse numpy array it doesn't take up dramatically more space?

**Comment by phildarnowsky** [comment]
It now comes to 26GB all told, which, IIRC, it was at about 11GB beforehand.

**Review by losvedir — APPROVED** [review]
👍

**Pull request merged**
